name: breakout_packager
description: A simple CLI to package multiple .bol files into one .h file
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  toml: ^0.11.0

dev_dependencies:
  pedantic: ^1.10.0
